### ISSUE TITLE
Add "geopoint" datapackage for testing

### ISSUE THREAD

**Issue by anuveyatsu** [frictionlessdata/test-data#2]
As a Developer I want to have a sample datapackage that contains "geopint" data so I can use it in my tests.

CSV data would look like similar to this:

```
default,array,object
"90, 45","[90, 45]","{"lon": 90, "lat": 45}"
"90, 46","[90, 46]","{"lon": 90, "lat": 46}"
```

however, this won't work straight away as we need to specify `quoteChar` for the CSV to be a single quote - see "object" field we need double quotes in the values. We also can specify `escapeChar` for CSV.

The "datapackage.json" would look like this:

```json
{
  "name": "geopoints-formats",
  "resources": [
    {
      "path": "data.csv",
      "name": "geopoint-data",
      "format": "csv",
      "schema": {
        "fields": [
          {
            "name": "default",
            "type": "geopoint",
            "format": "default"
          },
          {
            "name": "array",
            "type": "geopoint",
            "format": "array"
          },
          {
            "name": "object",
            "type": "geopoint",
            "format": "object"
          }
        ],
        "missingValues": [
          ""
        ]
      }
    }
  ]
}
```

**Comment by Stephen-Gates** [comment]
Here you go https://github.com/Stephen-Gates/data-package-examples/tree/master/test-geopoint for a start however fails with goodtables https://goodtables.io/github/Stephen-Gates/data-package-examples

**Comment by roll** [comment]
https://github.com/frictionlessdata/datasets/tree/master/packages/geopoint
