### ISSUE TITLE
Move the "datapackage.json" files

### ISSUE THREAD

**Issue by AcckiyGerman** [frictionlessdata/test-data#6]
Due to datapackage specifications we cannot use `../../` backwards in the `resources.path`.
The `data-cli` also returns an error when user tries to push a `dp.json` with such a path.

## Tasks

* [x] move data-files in the proper "packages" folders, so we don't need to use `../` in the path
* [x] fix the `path` in the `resources` section for all the `datapackage.json`

**Comment by AcckiyGerman** [comment]
FIXED: all the `datapackage.json` files are now have no `../` backward paths
https://github.com/frictionlessdata/test-data/commit/bf52cf9d6657bcdca0ed704e92789c5bd10b611d

**Comment by zelima** [comment]
@AcckiyGerman please don't label issues as invalid cause it's about invalid data, but if issue by itself is about something that is out of scope or something that should not be fixed.

**Comment by AcckiyGerman** [comment]
Ok
